spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
  mvc.throw-exception-if-no-handler-found: true
  web.resources.add-mappings: false

external:
  provider:
    kakao:
      url: https://dapi.kakao.com/v2/search/blog.json
      key: 8c0fa2ac614e802db6f336b676a8468e
    naver:
      url: https://openapi.naver.com/v1/search/blog.json
      client-id: vyBjLBntamQEtpAhJjBR
      client-secret: 4ruRd1CZqT
  circuit:
    main: KAKAO
    fallback: NAVER

core:
  ranking:
    consumer:
      size: 10

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-type: count_based
        sliding-window-size: 100
        minimum-number-of-calls: 100
        failure-rate-threshold: 50
        slow-call-rate-threshold: 100
        slow-call-duration-threshold: 10000 # customized from 600000
        permitted-number-of-calls-in-half-open-state: 10
        max-wait-duration-in-half-open-state: 1
        wait-duration-in-open-state: 30000